/* Bitaxus editorial fintech: navegación clara, acciones visibles y estados interactivos. */
import { useState } from "react";
import Recaudos from "./Recaudos";
import Contrapartes from "./Contrapartes";
import Global from "./Global";
import Pagos from "./Pagos";
import { toast } from "sonner";
import { ArrowDownLeft, ArrowLeftRight, ArrowRight, ArrowUpRight, Bell, Building2, Check, ChevronDown, ChevronRight, ClipboardList, Globe2, Home as HomeIcon, LayoutGrid, Menu, Plus, Settings, UsersRound, X, Clock3, Info } from "lucide-react";

const nav = [[HomeIcon, "Inicio"], [ArrowDownLeft, "Recaudos"], [ArrowLeftRight, "Pagos y dispersiones"], [UsersRound, "Contrapartes"], [Globe2, "Bitaxus Global"], [LayoutGrid, "Reportes"], [Settings, "Configuración"]] as const;
const activity = [
  { icon: ArrowDownLeft, tone: "green", title: "Recaudo identificado", subtitle: "Juan Perez", ref: "Referencia #RC-12984", time: "Hoy, 9:30 a. m.", amount: "$ 1.250.000", status: "CONFIRMADO" },
  { icon: ArrowUpRight, tone: "coral", title: "Pago programado", subtitle: "Proveedor Tech", ref: "Referencia #PA-SS21", time: "Ayer, 4:10 p. m.", amount: "$ 850.000", status: "EN PROCESO" },
  { icon: Globe2, tone: "purple", title: "Operación Global", subtitle: "USD → COP", ref: "Referencia #QG-24871", time: "Ayer, 2:40 p. m.", amount: "$ 3.912.000", status: "CONFIRMADO" },
  { icon: UsersRound, tone: "blue", title: "Dispersión procesada", subtitle: "Equipo comercial (12 beneficiarios)", ref: "Referencia #DS-96541", time: "Ayer, 12:20 p. m.", amount: "$ 7.500.000", status: "PROCESADA" },
];
function Icon({ icon: IconComp, tone = "slate" }: { icon: any; tone?: string }) { return <span className={`icon-bubble ${tone}`}><IconComp size={15} strokeWidth={2.1} /></span>; }

export default function Home() {
  const [active, setActive] = useState("Inicio");
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [period, setPeriod] = useState("Este mes");
  const [company, setCompany] = useState("OnTarget SAS");
  const [summaryVisible, setSummaryVisible] = useState(true);
  const [notificationOpen, setNotificationOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [modal, setModal] = useState<{ title: string; text: string } | null>(null);

  const closePopovers = () => { setNotificationOpen(false); setProfileOpen(false); };
  const chooseNav = (label: string) => { setActive(label); setSidebarOpen(false); closePopovers(); if (label !== "Inicio") toast(`${label} seleccionado`, { description: "Esta sección está lista para conectarse a datos reales." }); };
  const quickAction = (title: string, text = "Completa los datos de la operación para continuar.") => { closePopovers(); setModal({ title, text }); };
  const handlePeriod = (value: string) => { setPeriod(value); toast(`Periodo actualizado: ${value}`); };

  return <div className="app-shell" style={{ backgroundImage: `url(${import.meta.env.BASE_URL}assets/bitaxus-texture.webp)` }}>
    <aside className={`sidebar ${sidebarOpen ? "open" : ""}`}>
      <div className="brand"><img src={`${import.meta.env.BASE_URL}assets/bitaxus-mark.webp`} alt="" /><span>BITAXUS</span></div>
      <button className="mobile-close" onClick={() => setSidebarOpen(false)} aria-label="Cerrar menú"><X size={18} /></button>
      <nav className="nav-list" aria-label="Navegación principal">{nav.map(([IconComp, label]) => <button key={label} className={`nav-item ${active === label ? "active" : ""}`} onClick={() => chooseNav(label)}><IconComp size={15} />{label}</button>)}</nav>
      <div className="agent-card"><div className="agent-head"><span className="agent-icon"><ClipboardList size={14}/></span><b>Agente Bitaxus</b></div><p>¿Necesitas ayuda con una operación?</p><button onClick={() => quickAction("Agente Bitaxus", "Escribe tu consulta y un agente te ayudará con la operación.")}>Abrir chat <ArrowRight size={13}/></button></div>
    </aside>
    {sidebarOpen && <button className="backdrop" onClick={() => setSidebarOpen(false)} aria-label="Cerrar menú" />}
    <main className="main-content">
      <header className="topbar"><div className="mobile-title"><button className="menu-button" onClick={() => setSidebarOpen(true)} aria-label="Abrir menú"><Menu size={20}/></button><div><h1>Hola, Alejandra</h1><p>Este es el estado de tu operación.</p></div></div><div className="top-actions"><label className="select-wrap"><Building2 size={13}/><select value={company} onChange={e => { setCompany(e.target.value); toast(`Empresa cambiada a ${e.target.value}`); }}><option>OnTarget SAS</option><option>Andina Corp.</option><option>Beta Holdings</option></select><ChevronDown size={12}/></label><label className="select-wrap"><ClipboardList size={13}/><select value={period} onChange={e => handlePeriod(e.target.value)}><option>Este mes</option><option>Últimos 30 días</option><option>Este trimestre</option></select><ChevronDown size={12}/></label><div className="popover-wrap"><button className="icon-button notification" onClick={() => { setNotificationOpen(!notificationOpen); setProfileOpen(false); }} aria-label="Notificaciones"><Bell size={16}/><i>3</i></button>{notificationOpen && <div className="popover notification-popover"><b>Notificaciones</b><span>3 operaciones necesitan revisión.</span><button onClick={() => { setActive("Pagos y dispersiones"); closePopovers(); }}>Ver pendientes <ArrowRight size={13}/></button></div>}</div><div className="popover-wrap"><button className="avatar" onClick={() => { setProfileOpen(!profileOpen); setNotificationOpen(false); }}>A</button>{profileOpen && <div className="popover profile-popover"><b>Alejandra</b><span>{company}</span><button onClick={() => quickAction("Preferencias", "Aquí podrás cambiar tus preferencias de cuenta.")}>Preferencias</button><button onClick={() => toast("Sesión protegida")}>Cerrar sesión</button></div>}</div><ChevronDown size={13} className="avatar-chevron" /></div></header>
      {active === "Recaudos" ? <Recaudos onNavigate={setActive} /> : active === "Contrapartes" ? <Contrapartes /> : active === "Bitaxus Global" ? <Global onNavigate={setActive} /> : active === "Pagos y dispersiones" ? <Pagos onNavigate={setActive} /> : active !== "Inicio" ? <section className="section-view panel"><div className="section-icon"><Icon icon={nav.find(([, label]) => label === active)?.[0] || Info} tone="coral"/></div><h2>{active}</h2><p>Esta sección está preparada para conectarse con tu API. Desde aquí podrás gestionar y consultar la información de {active.toLowerCase()}.</p><button className="primary-action" onClick={() => quickAction(`Nueva operación en ${active}`)}><Plus size={15}/> Crear operación</button><button className="back-action" onClick={() => setActive("Inicio")}>Volver al inicio</button></section> : <>
        {summaryVisible && <section className="summary-card panel"><div className="summary-head"><div><p className="eyebrow">Actividad del periodo</p><div className="total">$ 2.560.000 <small>COP</small></div><p className="positive"><ArrowUpRight size={13}/> 12,5% <span>vs. 1–30 de abril de 2025</span></p></div><button className="hide-button" onClick={() => setSummaryVisible(false)}><Info size={12}/> Ocultar</button></div><div className="metrics"><div className="metric"><Icon icon={ArrowDownLeft} tone="green"/><div><span>Entradas</span><b>$ 1.550.000 <small>COP</small></b><em>+6,3% <i>vs. periodo anterior</i></em></div></div><div className="metric"><Icon icon={ArrowUpRight} tone="coral"/><div><span>Salidas</span><b>$ 1.020.000 <small>COP</small></b><em className="red">+4,1% <i>vs. periodo anterior</i></em></div></div><div className="metric"><Icon icon={Clock3} tone="amber"/><div><span>En proceso</span><b>12 <small>OPERACIONES</small></b><p>Operaciones pendientes de confirmación</p></div></div></div></section>}
        {!summaryVisible && <button className="show-summary" onClick={() => setSummaryVisible(true)}>Mostrar resumen <ChevronDown size={13}/></button>}
        <section className="quick-actions"><button onClick={() => quickAction("Programar recaudo")}><Icon icon={Plus} tone="green"/><b>Programar recaudo</b><ChevronRight size={15}/></button><button onClick={() => quickAction("Programar pago")}><Icon icon={ArrowUpRight} tone="blue"/><b>Programar pago</b><ChevronRight size={15}/></button><button onClick={() => quickAction("Consultar en Global", "Selecciona la moneda y el país de origen para iniciar una consulta.")}><Icon icon={Globe2} tone="purple"/><b>Consultar en Global</b><ChevronRight size={15}/></button></section>
        <section className="lower-grid"><div className="panel activity-card"><div className="card-heading"><h2>Actividad reciente</h2><button onClick={() => toast("Actividad actualizada")} aria-label="Actualizar actividad"><ChevronDown size={15}/></button></div><div className="activity-list">{activity.map(item => <button className="activity-row" key={item.title} onClick={() => quickAction(item.title, `${item.ref} · ${item.time}`)}><Icon icon={item.icon} tone={item.tone}/><div className="activity-main"><b>{item.title}</b><span>{item.subtitle}</span></div><div className="activity-ref"><span>{item.ref}</span><span>{item.time}</span></div><div className="activity-amount"><b className={item.status === "CONFIRMADO" ? "money-green" : ""}>{item.amount}</b><span className={`status ${item.status.toLowerCase().replace(" ", "-")}`}>{item.status}</span></div><ChevronRight size={14}/></button>)}</div><button className="view-all" onClick={() => setActive("Reportes")}>Ver todas las operaciones <ArrowRight size={14}/></button></div>
          <div className="panel review-card"><div className="card-heading"><h2>Por revisar <span className="count">4</span></h2><button onClick={() => toast("Revisiones actualizadas")} aria-label="Actualizar pendientes"><ChevronDown size={15}/></button></div><div className="review-list"><button onClick={() => quickAction("2 pagos pendientes", "Revisa y aprueba los pagos pendientes para continuar.")}><Icon icon={ArrowLeftRight} tone="coral"/><div><b>2 pagos pendientes</b><span>Espera tu aprobación para continuar.</span></div><strong>2</strong><ChevronRight size={14}/></button><button onClick={() => quickAction("1 recaudo sin relacionar")}><Icon icon={Clock3} tone="amber"/><div><b>1 recaudo sin relacionar</b><span>Hay pagos pendientes de ser identificados.</span></div><strong className="amber-text">1</strong><ChevronRight size={14}/></button><button onClick={() => quickAction("1 beneficiario incompleto")}><Icon icon={Info} tone="blue"/><div><b>1 beneficiario incompleto</b><span>Completa los datos para operar.</span></div><strong className="blue-text">1</strong><ChevronRight size={14}/></button></div><button className="view-all" onClick={() => setActive("Reportes")}>Ver todas las operaciones <ArrowRight size={14}/></button></div></section>
      </>}
    </main>
    {modal && <div className="modal-backdrop" onClick={() => setModal(null)}><div className="action-modal" onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setModal(null)} aria-label="Cerrar"><X size={17}/></button><div className="modal-icon"><Check size={18}/></div><h2>{modal.title}</h2><p>{modal.text}</p><label>Descripción<textarea placeholder="Añade una nota o descripción..." /></label><div className="modal-actions"><button className="secondary-action" onClick={() => setModal(null)}>Cancelar</button><button className="primary-action" onClick={() => { setModal(null); toast("Acción guardada", { description: "La operación quedó registrada para continuar." }); }}><Check size={14}/> Continuar</button></div></div></div>}
  </div>;
}
